server:
  port: 12345
spring:
  application:
    name: consumer-demo
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  sharding-jdbc:
    datasource-name: sharding
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sharding?zeroDateTimeBehavior=convertToNull&unicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&useSSL=false
    username: root
    password: root
